# yaml-language-server: $schema=https://spec.openapis.org/oas/3.1/schema/2021-05-20
---
# for the intellisense
openapi: "3.1.0"
info: { title: "", version: "" }

paths:
  Path:
    get:
      summary: "사용자의 스트릭 및 문제를 푼 날 정보 가져오기"
      description: "사용자가 문제를 푼 날, 스트릭 정보, 스트릭 테마를 가져옵니다."
      tags:
        - user
      operationId: getGrass

      parameters:
        - name: "handle"
          in: "query"
          description: "사용자 ID"
          required: true
          schema:
            type: "string"
        - name: "topic"
          in: "query"
          description: "아직 밝혀지지 않았습니다. 항상 `today-solved`입니다."
          required: true
          schema:
            type: "string"
      responses:
        "200":
          description: "서버가 반환에 성공한 경우입니다."
          content:
            application/json:
              schema:
                $ref: "../../schemas/full-user.yaml#/components/schemas/FullUser"
