# yaml-language-server: $schema=https://spec.openapis.org/oas/3.1/schema/2021-05-20
---
# for the intellisense
openapi: "3.1.0"
info: { title: "", version: "" }

paths:
  Path:
    get:
      summary: "상위 100문제 가져오기"
      description: "사용자가 푼 문제 중 상위 100문제를 가져옵니다."
      tags:
        - user
      operationId: getTop100

      parameters:
        - name: "handle"
          in: "query"
          description: "사용자 ID"
          required: true
          schema:
            type: "string"

      responses:
        "200":
          description: "서버가 반환에 성공한 경우입니다." 
          content:
            application/json:
              schema:
                type: "object"
                properties:
                  count:
                    description: "문제 수입니다."
                    type: "integer"
                    format: "int64"
                    example: 1
                    maximum: 100
                  items:
                    description: "문제 목록입니다."
                    type: "array"
                    items:
                      $ref: "../../schemas/tagged-problem.yaml#/components/schemas/TaggedProblem"
