# yaml-language-server: $schema=https://spec.openapis.org/oas/3.1/schema/2021-05-20
---
# for the intellisense
openapi: "3.1.0"
info: { title: "", version: "" }

paths:
  Path:
    post:
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: "object"
              properties:
                code:
                  description: "리딤 코드입니다."
                  type: "string"
                  example: "R33D3MC0D3"

      responses:
        "403":
          description: ""
        "404":
          description: ""
        # TODO: 반환에 성공한 경우
