# yaml-language-server: $schema=https://spec.openapis.org/oas/3.1/schema/2021-05-20
---
# for the intellisense
openapi: "3.1.0"
info: { title: "", version: "" }

paths:
  Path:
    patch:
      summary: "계정 설정 변경하기"
      description: |
        계정의 설정을 변경합니다.

        **주의**: 로그인이 필요한 API는 사이트 내에서 호출할 수 없으므로 별도 도구를 이용해주십시오.
      tags:
        - account
      operationId: updateAccountSettings

      security:
        - solvedacToken: []

      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: "object"
              properties:
                key:
                  description: "업데이트할 설정의 이름입니다."
                  type: "string"
                  example: "twitterPostOnClassIncrease"
                value:
                  description: "업데이트할 설정의 새로운 값입니다."
                  example: "true"

      responses:
        "403":
          description: "solvedacToken이 올바르지 않은 경우입니다."
        "204":
          description: "서버가 반환에 성공한 경우입니다."
