# yaml-language-server: $schema=https://spec.openapis.org/oas/3.1/schema/2021-05-20
---
# for the intellisense
openapi: "3.1.0"
info: { title: "", version: "" }

paths:
  Path:
    get:
      summary: "로그인 정보 가져오기"
      description: "현재 로그인한 계정 정보를 가져옵니다."
      tags:
        - account
      operationId: verifyAccountCredentials

      security:
        - solvedacToken: []

      responses:
        "403":
          description: "solvedacToken이 올바르지 않은 경우입니다."
        "200":
          description: "서버가 반환에 성공한 경우입니다."
          content:
            application/json:
              schema:
                type: "object"
                properties:
                  user:
                    description: "계정의 사용자 정보입니다."
                    allOf:
                      - $ref: "../../schemas/user.yaml#/components/schemas/User"
                      - type: "object"
                        properties:
                          settings:
                            $ref: "../../schemas/settings.yaml#/components/schemas/Settings"
                          email:
                            description: "계정의 이메일 주소입니다."
                            type: "string"
                            format: "email"
                            example: "kiwiyou.dev@gmail.com"
                  solved:
                    description: "해당 계정의 사용자가 푼 문제 정보입니다."
                    type: "array"
                    items:
                      type: "object"
                      properties:
                        id:
                          description: "문제 ID입니다."
                          type: "number"
                          example: 1002
                        status:
                          description: |
                            현재 문제 풀이 상태입니다. 알려진 값은 다음이 있습니다.
                            `"solved"`, `"tried"`
                          type: "string"
                          example: "tried"
