# yaml-language-server: $schema=https://spec.openapis.org/oas/3.1/schema/2021-05-20
---
# for the intellisense
openapi: "3.1.0"
info: { title: "", version: "" }

paths:
  Path:
    get:
      summary: "검색 자동완성 구하기"
      description: "주어진 쿼리에 따라 검색해보고, 자동 완성에 적합하도록 가공한 정보를 돌려줍니다."
      tags:
        - search
      operationId: getSearchAutoCompletion

      parameters:
        - name: "query"
          in: "query"
          description: "쿼리 문자열"
          required: true
          schema:
            type: "string"

      responses:
        "200":
          description: "서버가 반환에 성공한 경우입니다."
          content:
            application/json:
              schema:
                type: "object"
                properties:
                  autocomplete:
                    type: "array"
                    items:
                      type: "object"
                      properties:
                        caption:
                          description: "자동완성 제목입니다. 해당 값으로 자동완성됩니다."
                          type: "string"
                        description:
                          description: "자동완성 요소에 대한 설명입니다."
                          type: "string"
                  problems:
                    description: "찾은 문제 목록입니다."
                    type: "array"
                    items:
                      $ref: "../../schemas/problem.yaml#/components/schemas/Problem"
                  problemCount:
                    description: "찾은 문제 수입니다."
                    type: "integer"
                    format: "int64"
                    example: 1
                  users:
                    description: "찾은 사용자 목록입니다."
                    type: "array"
                    items:
                      $ref: "../../schemas/user.yaml#/components/schemas/User"
                  userCount:
                    description: "찾은 사용자 수입니다."
                    type: "integer"
                    format: "int64"
                    example: 1
                  tags:
                    description: "찾은 태그 목록입니다."
                    type: "array"
                    items:
                      $ref: "../../schemas/problem-tag.yaml#/components/schemas/ProblemTag"
                  tagCount:
                    description: "찾은 태그 수입니다."
                    type: "integer"
                    format: "int64"
                    example: 1
