# yaml-language-server: $schema=https://spec.openapis.org/oas/3.1/schema/2021-05-20
---
# for the intellisense
openapi: "3.1.0"
info: { title: "", version: "" }

paths:
  Path:
    get:
      summary: "사용자 검색하기"
      description: "주어진 쿼리에 따라 사용자를 검색합니다."
      tags:
        - "검색"
      operationId: searchUser

      parameters:
        - name: "query"
          in: "query"
          description: "쿼리 문자열"
          required: true
          schema:
            type: "string"
        - name: "page"
          in: "query"
          description: "페이지"
          schema:
            type: "number"

      responses:
        "200":
          description: "서버가 반환에 성공한 경우입니다."
          content:
            application/json:
              schema:
                type: "object"
                properties:
                  count:
                    description: "찾은 사용자 수입니다."
                    type: "integer"
                    format: "int64"
                    example: 1
                  items:
                    description: "찾은 사용자 목록입니다."
                    type: "array"
                    items:
                      $ref: "../../schemas/ranked-user.yaml#/components/schemas/Schema"
