# yaml-language-server: $schema=https://spec.openapis.org/oas/3.1/schema/2021-05-20
---
# for the intellisense
openapi: "3.1.0"
info: { title: "", version: "" }

paths:
  Path:
    get:
      summary: "CLASS별 문제 수 가져오기"
      description: "문제 개수를 문제 CLASS별로 가져옵니다."
      tags:
        - problem
      operationId: getClassProblemCount

      responses:
        "200":
          description: "서버가 반환에 성공한 경우입니다."
          content:
            application/json:
              schema:
                type: "array"
                items:
                  type: "object"
                  properties:
                    class:
                      type: "integer"
                      format: "int64"
                      minimum: 1
                      maximum: 10
                    total:
                      type: "integer"
                      format: "int64"
                      minimum: 0
                      description: "이 CLASS에 속한 에센셜이 아닌 문제 수입니다."
                      example: 36
                    essentials:
                      type: "integer"
                      format: "in64"
                      minimum: 0
                      description: "이 CLASS에 속한 에센셜 문제 수입니다."
                      example: 16
                    criteria:
                      type: "integer"
                      format: "in64"
                      minimum: 0
                      description: "이 CLASS를 취득하기 위한 최소 문제 수입니다."
                      example: 16
