# yaml-language-server: $schema=https://spec.openapis.org/oas/3.1/schema/2021-05-20
---
# for the intellisense
openapi: "3.1.0"
info: { title: "", version: "" }

paths:
  Path:
    get:
      summary: "ID 목록으로 문제 목록 가져오기"
      description: "해당하는 ID의 문제 목록을 가져옵니다."
      tags:
        - problem
      operationId: getProblemByIdArray
      parameters:
        - name: "problemIds"
          description: "쉼표로 구분한 문제 ID 목록"
          in: "query"
          required: true
          schema:
            type: "string"
      responses:
        "200":
          description: "서버가 반환에 성공한 경우입니다."
          content:
            application/json:
              schema:
                type: "array"
                items:
                  $ref: "../../schemas/tagged-problem.yaml#/components/schemas/TaggedProblem"
