# yaml-language-server: $schema=https://spec.openapis.org/oas/3.1/schema/2021-05-20
---
# for the intellisense
openapi: "3.1.0"
info: { title: "", version: "" }

paths:
  Path:
    get:
      summary: "ID로 문제 가져오기"
      description: "해당하는 ID의 문제를 가져옵니다."
      tags:
        - problem
      operationId: getProblemById
      parameters:
        - name: "problemId"
          description: "문제 ID"
          in: "query"
          required: true
          schema:
            type: "integer"
            format: "int64"
      responses:
        "200":
          description: "서버가 반환에 성공한 경우입니다."
          content:
            application/json:
              schema:
                $ref: "../../schemas/tagged-problem.yaml#/components/schemas/Schema"
