# yaml-language-server: $schema=https://spec.openapis.org/oas/3.1/schema/2021-05-20
---
# for the intellisense
openapi: "3.1.0"
info: { title: "", version: "" }

components:
  schemas:
    Background:
      title: Background
      description: |
        사용자가 사용할 수 있는 배경입니다.
      type: "object"
      required:
        - backgroundId
        - backgroundImageUrl
        - unlockedUserCount
        - displayName
        - displayDescription
        - conditions
        - hiddenConditions
        - isIllust
        - authors
      properties:
        backgroundId:
          description: "배경의 ID입니다."
          type: "string"
          example: "hanbyeol_stars"
        backgroundImageUrl:
          description: "배경 사진으로 가는 하이퍼링크입니다."
          type: "string"
          example: "https://static.solved.ac/profile_bg/hanbyeol_stars/hanbyeol_stars.jpg"
        fallbackBackgroundImageUrl:
          description: "배경 사진이 없을 때 대체로 사용할 사진으로 가는 하이퍼링크입니다."
          type: "string"
          nullable: true
          example: null
        backgroundVideoUrl:
          description: "배경 비디오로 가는 하이퍼링크입니다."
          type: "string"
          nullable: true
          example: null
        unlockedUserCount:
          description: "해당 배경을 획득한 사용자의 수입니다."
          type: "integer"
          format: "int64"
          example: 1394
        displayName:
          description: "배경의 이름입니다."
          type: "string"
          example: "Stars in the Evening Sky"
        displayDescription:
          description: "배경의 설명입니다."
          type: "string"
          example: "She who has a star in her heart never gets lost in the dark"
        conditions:
          description: "해당 배경을 얻을 수 있는 조건입니다."
          type: "string"
          example: "Bought the background at the coin shop"
        hiddenConditions:
          description: "해당 배경을 얻을 수 있는 조건이 숨겨져 있는지 여부입니다."
          type: "boolean"
          example: false
        isIllust:
          description: "해당 배경이 일러스트인지 여부입니다."
          type: "boolean"
          example: true
        authors:
          description: "해당 배경을 만든 사람들의 정보입니다."
          type: "array"
          items:
            type: "object"
            properties:
              authorId:
                description: "작가의 ID입니다."
                type: "string"
                example: "havana723"
              role:
                description: "작가의 역할입니다."
                type: "string"
                example: "Illustration"
              authorUrl:
                description: "작가의 홈페이지로 가는 하이퍼링크입니다."
                type: "string"
                nullable: true
                example: null
              handle:
                description: "작가의 사용자 ID입니다."
                type: "string"
                example: "havana723"
              twitter:
                description: "작가의 트위터 ID입니다."
                type: "string"
                nullable: true
                example: null
              instagram:
                description: "작가의 인스타그램 ID입니다."
                type: "string"
                nullable: true
                example: null
              displayName:
                description: "작가의 이름입니다."
                type: "string"
                example: "havana723"
