# yaml-language-server: $schema=https://spec.openapis.org/oas/3.1/schema/2021-05-20
---
# for the intellisense
openapi: "3.1.0"
info: { title: "", version: "" }

components:
  schemas:
    FullUser:
      title: FullUser
      description: |
        사용자 정보입니다.
      allOf:
        - $ref: "./user.yaml#/components/schemas/User"
        - type: "object"
          properties:
            isRival:
              description: "라이벌 여부입니다."
              type: "boolean"
            isReverseRival:
              description: "역라이벌 여부입니다."
              type: "boolean"
            blocked:
              description: "차단 여부입니다."
              type: "boolean"
            reverseBlocked:
              description: "역차단 여부입니다."
              type: "boolean"
