# yaml-language-server: $schema=https://spec.openapis.org/oas/3.1/schema/2021-05-20
---
# for the intellisense
openapi: "3.1.0"
info: { title: "", version: "" }

components:
  schemas:
    Item:
      title: Item
      description: |
        사용자가 사용할 수 있는 아이템입니다.
      type: "object"
      required:
        - itemId
        - itemImageUrl
        - inventoryMaxUnits
        - usable
        - displayName
        - displayDescription
      properties:
        itemId:
          description: "아이템의 ID입니다."
          type: "string"
          example: "streak-freeze"
        itemImageUrl:
          description: "아이템 사진으로 가는 하이퍼링크입니다."
          type: "string"
          example: "https://static.solved.ac/item/freeze-small-simple.svg"
        inventoryMaxUnits:
          description: "최대 소유 가능 개수입니다. 호출자에 따라 달라질 수 있습니다."
          type: "integer"
          example: 2
        usable:
          description: "아이템 사용 가능 여부입니다."
          type: "boolean"
          example: "true"
        displayName:
          description: "아이템의 이름입니다."
          type: "string"
          example: "스트릭 프리즈"
        displayDescription:
          description: "아이템의 설명입니다."
          type: "string"
          example: "미리 장착해 두면 어제 문제 푸는 걸 잊었더라도 스트릭이 깨지지 않습니다. 단, 스트릭 길이가 늘어나지는 않습니다.\n인벤토리에서 장착해서 사용할 수 있습니다."
