# yaml-language-server: $schema=https://spec.openapis.org/oas/3.1/schema/2021-05-20
---
# for the intellisense
openapi: "3.1.0"
info: { title: "", version: "" }

components:
  schemas:
    Schema:
      type: "object"
      properties:
        organizationId:
          description: "조직의 ID입니다."
          type: "integer"
          format: "int64"
          example: 1082
        name:
          description: "조직의 이름입니다."
          type: "string"
          example: "solved.ac"
        type:
          description: "조직의 구분입니다."
          type: "string"
          enum: ["community", "university", "company", "high_school"]
        rating:
          descripton: "조직의 레이팅입니다."
          type: "integer"
          format: "int64"
          example: 2321
        userCount:
          description: "조직에 포함된 사용자의 수입니다."
          type: "integer"
          format: "int64"
          example: 2
        voteCount:
          description: "조직의 총 난이도 기여 수입니다."
          type: "integer"
          format: "int64"
          example: 1518
        solvedCount:
          description: "조직의 총 푼 문제 수입니다."
          type: "integer"
          format: "int64"
          example: 2729
        color:
          description: "조직의 색깔입니다."
          type: "string"
          example: "#000000"
