# yaml-language-server: $schema=https://spec.openapis.org/oas/3.1/schema/2021-05-20
---
# for the intellisense
openapi: "3.1.0"
info: { title: "", version: "" }

components:
  schemas:
    Schema:
      type: "object"
      description: |
        문제 정보입니다.
      properties:
        problemId:
          description: "문제 ID입니다."
          type: "integer"
          format: "int64"
          example: 13705
        titleKo:
          description: "한국어 문제 제목입니다. HTML 엔티티나 LaTeX 수식을 포함할 수 있습니다."
          type: "string"
          example: "Ax+Bsin(x)=C"
        isSolvable:
          description: "채점 가능 여부입니다."
          type: "boolean"
          example: true
        isPartial:
          description: "부분 점수 혹은 서브태스크 문제 여부입니다."
          type: "boolean"
          example: false
        acceptedUserCount:
          description: "맞은 사람 수입니다."
          type: "integer"
          format: "int64"
          example: 189
        level:
          allOf:
            - $ref: "./problem-level.yaml#/components/schemas/Schema"
            - description: "문제 수준입니다."
        votedUserCount:
          description: "난이도 기여자의 수입니다."
          type: "integer"
          format: "int64"
          example: 62
        isLevelLocked:
          description: "난이도 기여 제한 여부입니다."
          type: "boolean"
          example: false
        averageTries:
          description: "평균 시도 횟수입니다."
          type: "number"
          example: 28.8413
