# yaml-language-server: $schema=https://spec.openapis.org/oas/3.1/schema/2021-05-20
---
# for the intellisense
openapi: "3.1.0"
info: { title: "", version: "" }

components:
  schemas:
    Problem:
      title: Problem
      type: "object"
      description: |
        문제 정보입니다.
      properties:
        problemId:
          description: "문제 ID입니다."
          type: "integer"
          format: "int64"
          example: 13705
        titleKo:
          description: "한국어 문제 제목입니다. HTML 엔티티나 LaTeX 수식을 포함할 수 있습니다."
          type: "string"
          example: "Ax+Bsin(x)=C"
        titles:
          description: "언어별 문제 제목입니다."
          type: "array"
          items:
            type: "object"
            properties:
              language:
                $ref: "./language.yaml#/components/schemas/Language"
              languageDisplayName:
                description: "표시되는 언어의 이름입니다."
                type: "string"
                example: "ko"
              title:
                description: "문제의 제목입니다."
                type: "string"
                example: "Ax+Bsin(x)=C"
              isOriginal:
                description: "원본과 동일한지 여부입니다."
                type: "boolean"
                example: true
        isSolvable:
          description: "채점 가능 여부입니다."
          type: "boolean"
          example: true
        isPartial:
          description: "부분 점수 혹은 서브태스크 문제 여부입니다."
          type: "boolean"
          example: false
        acceptedUserCount:
          description: "맞은 사람 수입니다."
          type: "integer"
          format: "int64"
          example: 423
        level:
          $ref: "./problem-level.yaml#/components/schemas/ProblemLevel"
        votedUserCount:
          description: "난이도 기여자의 수입니다."
          type: "integer"
          format: "int64"
          example: 129
        sprout:
          description: "새싹 문제인지 여부입니다."
          type: "boolean"
          example: false
        givesNoRating:
          description: "레이팅을 주지 않는지 여부입니다."
          type: "boolean"
          example: false
        isLevelLocked:
          description: "난이도 기여 제한 여부입니다."
          type: "boolean"
          example: false
        averageTries:
          description: "평균 시도 횟수입니다."
          type: "number"
          example: 26.5248
        official:
          description: "공식 문제 여부입니다."
          type: "boolean"
          example: true
