# yaml-language-server: $schema=https://spec.openapis.org/oas/3.1/schema/2021-05-20
---
# for the intellisense
openapi: "3.1.0"
info: { title: "", version: "" }

components:
  schemas:
    Schema:
      title: Settings
      description: "사용자의 solved.ac 설정 정보입니다."
      type: "object"
      properties:
        screenTheme:
          description: "사이트 디자인 테마입니다."
          type: "string"
          enum: ["default", "light", "dark", "black"]
        tagDisplayLanguage:
          allOf:
            - $ref: "./language.yaml#/components/schemas/Schema"
            - description: "태그 이름을 나타낼 때 사용할 언어입니다."
        iconSchemeSolved:
          allOf:
            - $ref: "./icon-scheme.yaml#/components/schemas/Schema"
            - description: "해결한 문제의 난이도 아이콘입니다."
        iconSchemeNotSolved:
          allOf:
            - $ref: "./icon-scheme.yaml#/components/schemas/Schema"
            - description: "해결하지 못한 문제의 난이도 아이콘입니다."
        problemSortBy:
          description: "문제 목록의 기본 정렬 순서입니다."
          type: "string"
          enum: ["id", "level", "title", "solved", "average_try", "random"]
        twitterPostHandle:
          description: "트윗에 핸들을 포함하는지 여부입니다."
          type: "string"
          format: "boolean"
          example: "true"
        twitterPostOnClassIncrease:
          description: "CLASS가 올랐을 때 트윗을 보내는지 여부입니다."
          type: "string"
          format: "boolean"
          example: "false"
        twitterPostOnProblemSolve:
          description: "문제를 처음 해결했을 때 트윗을 보내는지 여부입니다."
          type: "string"
          format: "boolean"
          example: "true"
        twitterPostOnRatingIncrease:
          description: "AC 레이팅이 올랐을 때 트윗을 보내는지 여부입니다."
          type: "string"
          format: "boolean"
          example: "false"
        twitterPostOnTierIncrease:
          description: "티어가 올랐을 때 트윗을 보내는지 여부입니다."
          type: "string"
          format: "boolean"
          example: "true"
