# yaml-language-server: $schema=https://spec.openapis.org/oas/3.1/schema/2021-05-20
---
# for the intellisense
openapi: "3.1.0"
info: { title: "", version: "" }

components:
  schemas:
    Schema:
      type: "object"
      properties:
        problemCount:
          description: "여태까지 색인된 백준 문제 수입니다."
          type: "integer"
          format: "int64"
          example: 20353
        problemVotedCount:
          description: "여태까지 난이도가 기여된 백준 문제 수입니다."
          type: "integer"
          format: "int64"
          example: 12463
        userCount:
          description: "여태까지 등록한 사용자 수입니다."
          type: "integer"
          format: "int64"
          example: 34249
        contributorCount:
          description: "여태까지 난이도에 기여한 사용자 수입니다."
          type: "integer"
          format: "int64"
          example: 1173
        contributionCount:
          description: "여태까지 이루어진 난이도 기여의 수입니다."
          type: "integer"
          format: "int64"
          example: 101172
