# yaml-language-server: $schema=https://spec.openapis.org/oas/3.1/schema/2021-05-20
---
# for the intellisense
openapi: "3.1.0"
info: { title: "", version: "" }

components:
  schemas:
    Schema:
      description: |
        사용자 정보입니다.
      type: "object"
      required:
        - handle
        - bio
        - organizations
        - background
        - profileImageUrl
        - solvedCount
        - voteCount
        - exp
        - tier
        - rating
        - ratingByProblemsSum
        - ratingByClass
        - ratingBySolvedCount
        - ratingByVoteCount
        - class
        - classDecoration
        - rivalCount
        - reverseRivalCount
        - maxStreak
      properties:
        handle:
          description: "사용자명입니다."
          type: "string"
          example: "shiftpsh"
        bio:
          description: "사용자의 자기소개입니다."
          type: "string"
          example: "🧡 이곳의 개발자입니다."
        organizations:
          description: "사용자가 속한 조직 목록입니다."
          type: "array"
          items:
            $ref: "./organization.yaml#/components/schemas/Schema"
        badge:
          allOf:
            - $ref: "./badge.yaml#/components/schemas/Schema"
            - description: "사용자가 지금 사용 중인 뱃지입니다."
        background:
          description: "사용자의 배경 사진입니다."
          type: "object"
          properties:
            backgroundId:
              description: "배경의 고유 ID입니다."
              type: "string"
              example: "balloon_002"
            backgroundImageUrl:
              description: "배경 사진으로 가는 하이퍼링크입니다."
              type: "string"
              example: "https://static.solved.ac/profile_bg/balloon_002/balloon_002.png"
            author:
              description: "배경의 제작자를 표시하는 문구입니다."
              type: "string"
              example: "Photo by Al Soot on Unsplash"
            authorUrl:
              description: "배경의 제작자와 관련된 사이트로 가는 하이퍼링크입니다."
              type: "string"
              example: "https://unsplash.com/photos/yRjLihK35Yw"
            displayName:
              description: "배경의 이름입니다."
              type: "string"
              example: "하늘을 수놓은 풍선"
            displayDescription:
              description: "배경의 설명입니다."
              type: "string"
              example: "assorted colored balloons mid airs"
        profileImageUrl:
          description: "사용자의 프로필 사진으로 가는 하이퍼링크입니다."
          type: "string"
          nullable: true
          example: "https://static.solved.ac/uploads/profile/0565b63f0b204e990d1b163018a1c358992519b8.png"
        solvedCount:
          description: "사용자가 푼 문제 수입니다."
          type: "integer"
          format: "int64"
          example: 2658
        voteCount:
          description: "사용자가 난이도 기여를 한 횟수입니다."
          type: "integer"
          format: "int64"
          example: 1326
        exp:
          description: "사용자가 여태까지 획득한 경험치량입니다."
          type: "integer"
          format: "int64"
          example: 498605585
        tier:
          $ref: "./user-tier.yaml#/components/schemas/Schema"
        rating:
          description: "사용자의 레이팅입니다."
          type: "integer"
          format: "int64"
          example: 2641
        ratingByProblemsSum:
          description: "푼 문제의 난이도 합으로 계산한 사용자의 레이팅입니다."
          type: "integer"
          format: "int64"
          example: 2211
        ratingByClass:
          description: "취득한 클래스에 따른 사용자의 레이팅입니다."
          type: "integer"
          format: "int64"
          example: 230
        ratingBySolvedCount:
          description: "푼 문제 수로 계산한 사용자의 레이팅입니다."
          type: "integer"
          format: "int64"
          example: 175
        ratingByVoteCount:
          description: "문제 난이도에 기여한 횟수로 계산한 사용자의 레이팅입니다."
          type: "integer"
          format: "int64"
          example: 25
        class:
          description: "사용자가 취득한 Class입니다."
          type: "integer"
          format: "int64"
          example: 8
        classDecoration:
          description: "사용자가 취득한 Class의 수준입니다."
          type: "string"
          enum: ["none", "silver", "gold"]
        rivalCount:
          description: "사용자의 라이벌 수입니다."
          type: "integer"
          format: "int64"
          example: 38
        reverseRivalCount:
          description: "사용자의 역라이벌 수입니다."
          type: "integer"
          format: "int64"
          example: 53
        maxStreak:
          description: "최대 연속 문제 풀이일 수입니다."
          type: "integer"
          format: "int64"
          example: 6
