# yaml-language-server: $schema=https://spec.openapis.org/oas/3.1/schema/2021-05-20
---
# for the intellisense
openapi: "3.1.0"
info: { title: "", version: "" }

components:
  schemas:
    User:
      title: User
      description: |
        사용자 정보입니다.
      type: "object"
      required:
        - handle
        - bio
        - organizations
        - backgroundId
        - profileImageUrl
        - solvedCount
        - voteCount
        - class
        - classDecoration
        - rivalCount
        - reverseRivalCount
        - tier
        - rating
        - ratingByProblemsSum
        - ratingByClass
        - ratingBySolvedCount
        - ratingByVoteCount
        - arenaTier
        - arenaRating
        - arenaMaxTier
        - arenaMaxRating
        - arenaCompetedRoundCount
        - maxStreak
        - coins
        - stardusts
        - joinedAt
        - bannedUntil
        - proUntil
        - rank
      properties:
        handle:
          description: "사용자명입니다."
          type: "string"
          example: "shiftpsh"
        bio:
          description: "사용자의 자기소개입니다."
          type: "string"
          example: "🧡 이곳의 개발자입니다."
        badgeId:
          description: "사용자가 지금 사용 중인 뱃지의 아이디입니다."
          type: "string"
          nullable: true
          example: "ghudegy2022-1"
        backgroundId:
          description: "사용자가 지금 사용 중인 배경의 아이디입니다."
          type: "string"
          example: "boardgame_7"
        profileImageUrl:
          description: "사용자의 프로필 사진으로 가는 하이퍼링크입니다."
          type: "string"
          nullable: true
          example: "https://static.solved.ac/uploads/profile/0565b63f0b204e990d1b163018a1c358992519b8.png"
        solvedCount:
          description: "사용자가 푼 문제 수입니다."
          type: "integer"
          format: "int64"
          example: 2658
        voteCount:
          description: "사용자가 난이도 기여를 한 횟수입니다."
          type: "integer"
          format: "int64"
          example: 1326
        tier:
          $ref: "./user-tier.yaml#/components/schemas/UserTier"
        rating:
          description: "사용자의 레이팅입니다."
          type: "integer"
          format: "int64"
          example: 2641
        ratingByProblemsSum:
          description: "푼 문제의 난이도 합으로 계산한 사용자의 레이팅입니다."
          type: "integer"
          format: "int64"
          example: 2211
        ratingByClass:
          description: "취득한 클래스에 따른 사용자의 레이팅입니다."
          type: "integer"
          format: "int64"
          example: 230
        ratingBySolvedCount:
          description: "푼 문제 수로 계산한 사용자의 레이팅입니다."
          type: "integer"
          format: "int64"
          example: 175
        ratingByVoteCount:
          description: "문제 난이도에 기여한 횟수로 계산한 사용자의 레이팅입니다."
          type: "integer"
          format: "int64"
          example: 25
        class:
          description: "사용자가 취득한 Class입니다."
          type: "integer"
          format: "int64"
          example: 8
        classDecoration:
          description: "사용자가 취득한 Class의 수준입니다."
          $ref: "./class-decoration.yaml#/components/schemas/ClassDecoration"
        rivalCount:
          description: "사용자의 라이벌 수입니다."
          type: "integer"
          format: "int64"
          example: 38
        reverseRivalCount:
          description: "사용자의 역라이벌 수입니다."
          type: "integer"
          format: "int64"
          example: 53
        maxStreak:
          description: "최대 연속 문제 풀이일 수입니다."
          type: "integer"
          format: "int64"
          example: 6
        coins:
          description: "사용자가 가지고 있는 코인의 수입니다."
          type: "integer"
          format: "int64"
          example: 3845
        stardusts:
          description: "사용자가 가지고 있는 별가루의 수입니다."
          type: "integer"
          format: "int64"
          example: 264680
        joinedAt:
          description: "사용자가 가입한 날짜입니다."
          type: "string"
          format: "date-time"
          example: "2021-06-19T00:00:00.000Z"
        bannedUntil:
          description: "사용자의 정지 종료 날짜입니다."
          type: "string"
          format: "date-time"
          example: "1970-01-01T00:00:00.000Z"
        proUntil:
          description: "사용자의 PRO 종료 날짜입니다."
          type: "string"
          format: "date-time"
          example: "9999-12-31T00:00:00.000Z"
        rank:
          description: "사용자의 순위입니다."
          type: "integer"
          format: "int64"
          example: 104
        arenaTier:
          description: "사용자의 아레나 티어입니다."
          type: "integer"
          format: "int64"
          example: 12
        arenaRating:
          description: "사용자의 아레나 레이팅입니다."
          type: "integer"
          format: "int64"
          example: 2641
        arenaMaxTier:
          description: "사용자의 아레나 최고 티어입니다."
          type: "integer"
          format: "int64"
          example: 12
        arenaMaxRating:
          description: "사용자의 아레나 최고 레이팅입니다."
          type: "integer"
          format: "int64"
          example: 2641