# yaml-language-server: $schema=https://spec.openapis.org/oas/3.1/schema/2021-05-20
---
# for the intellisense
openapi: "3.1.0"
info: { title: "", version: "" }

paths:
  Path:
    get:
      summary: "배경 정보 가져오기"
      description: "배경의 정보를 가져옵니다."
      tags:
        - background
      operationId: getBackground

      parameters:
        - name: "backgroundId"
          in: "query"
          description: "배경 ID"
          required: true
          schema:
            type: "string"

      responses:
        "200":
          description: "서버가 반환에 성공한 경우입니다."
          content:
            application/json:
              schema:
                $ref: "../../schemas/background.yaml#/components/schemas/Background"
