# yaml-language-server: $schema=https://spec.openapis.org/oas/3.1/schema/2021-05-20
---
openapi: "3.1.0"


tags:
  - name: "account"
    description: "계정과 관련이 있는 API입니다"
  - name: "badge"
    description: "뱃지와 관련이 있는 API입니다"
  - name: "background"
    description: "배경과 관련이 있는 API입니다"
  - name: "coins"
    description: "코인/별조각과 관련이 있는 API입니다"
  - name: "other"
    description: "아직 분류하지 못한 API입니다"
  - name: "problem"
    description: "문제와 관련이 있는 API입니다"
  - name: "search"
    description: "검색과 관련이 있는 API입니다"
  - name: "user"
    description: "사용자와 관련이 있는 API입니다"

paths:
  /account/verify_credentials:
    $ref: "./paths/account/verify_credentials.yaml#/paths/Path"
  /coins/exchange_rate:
    $ref: "./paths/coins/exchange_rate.yaml#/paths/Path"
  /coins/shop/list:
    $ref: "./paths/coins/shop/list.yaml#/paths/Path"
  /post/show:
    get:
      description: "TODO"
      responses:
        "200":
          description: "TODO"
  /ranking/tier:
    $ref: "./paths/ranking/tier.yaml#/paths/Path"
  /ranking/rival:
    $ref: "./paths/ranking/rival.yaml#/paths/Path"
  /ranking/organization:
    $ref: "./paths/ranking/organization.yaml#/paths/Path"
  /search/suggestion:
    $ref: "./paths/search/suggestion.yaml#/paths/Path"
  /tag/list:
    get:
      description: "TODO"
      responses:
        "200":
          description: "TODO"
  /user/class_stats:
    get:
      description: "TODO"
      responses:
        "200":
          description: "TODO"
  /user/contribution_stats:
    get:
      description: "TODO"
      responses:
        "200":
          description: "TODO"
  /user/organizations:
    $ref: "./paths/user/organizations.yaml#/paths/Path"
  /user/problem_stats:
    $ref: "./paths/user/problem_stats.yaml#/paths/Path"
  /user/problem_tag_stats:
    get:
      description: "TODO"
      responses:
        "200":
          description: "TODO"

components:
  schemas:
    CoinshopProduct:
      $ref: "./schemas/coinshop-product.yaml#/components/schemas/CoinshopProduct"
    IconScheme:
      $ref: "./schemas/icon-scheme.yaml#/components/schemas/IconScheme"
    Item:
      $ref: "./schemas/item.yaml#/components/schemas/Item"
    Organization:
      $ref: "./schemas/organization.yaml#/components/schemas/Organization"
    Settings:
      $ref: "./schemas/settings.yaml#/components/schemas/Settings"
