# yaml-language-server: $schema=https://spec.openapis.org/oas/3.1/schema/2021-05-20
---
openapi: "3.1.0"

paths:
  /account/verify_credentials:
    $ref: "./paths/account/verify_credentials.yaml#/paths/Path"
  /user/problem_stats:
    $ref: "./paths/user/problem_stats.yaml#/paths/Path"

components:
  schemas:
    IconScheme:
      $ref: "./schemas/icon-scheme.yaml#/components/schemas/IconScheme"
    Settings:
      $ref: "./schemas/settings.yaml#/components/schemas/Settings"
