# yaml-language-server: $schema=https://spec.openapis.org/oas/3.1/schema/2021-05-20
---
openapi: "3.1.0"

paths:
  /account/verify_credentials:
    $ref: "./paths/account/verify_credentials.yaml#/paths/Path"
  /coins/exchange_rate:
    $ref: "./paths/coins/exchange_rate.yaml#/paths/Path"
  /coins/shop/list:
    $ref: "./paths/coins/shop/list.yaml#/paths/Path"
  /post/show:
    get:
      description: "TODO"
      responses:
        "200":
          description: "TODO"
  /ranking/tier:
    $ref: "./paths/ranking/tier.yaml#/paths/Path"
  /ranking/organization:
    $ref: "./paths/ranking/organization.yaml#/paths/Path"
  /tag/list:
    get:
      description: "TODO"
      responses:
        "200":
          description: "TODO"
  /user/class_stats:
    get:
      description: "TODO"
      responses:
        "200":
          description: "TODO"
  /user/contribution_stats:
    get:
      description: "TODO"
      responses:
        "200":
          description: "TODO"
  /user/organizations:
    $ref: "./paths/user/organizations.yaml#/paths/Path"
  /user/problem_stats:
    $ref: "./paths/user/problem_stats.yaml#/paths/Path"
  /user/problem_tag_stats:
    get:
      description: "TODO"
      responses:
        "200":
          description: "TODO"

components:
  schemas:
    CoinshopProduct:
      $ref: "./schemas/coinshop-product.yaml#/components/schemas/CoinshopProduct"
    IconScheme:
      $ref: "./schemas/icon-scheme.yaml#/components/schemas/IconScheme"
    Item:
      $ref: "./schemas/item.yaml#/components/schemas/Item"
    Organization:
      $ref: "./schemas/organization.yaml#/components/schemas/Organization"
    Settings:
      $ref: "./schemas/settings.yaml#/components/schemas/Settings"
