# yaml-language-server: $schema=https://spec.openapis.org/oas/3.1/schema/2021-05-20
---
openapi: "3.1.0"


tags:
  - name: "account"
    description: "계정과 관련이 있는 API입니다"
  - name: "badge"
    description: "뱃지와 관련이 있는 API입니다"
  - name: "background"
    description: "배경과 관련이 있는 API입니다"
  - name: "coins"
    description: "코인/별조각과 관련이 있는 API입니다"
  - name: "other"
    description: "아직 분류하지 못한 API입니다"
  - name: "problem"
    description: "문제와 관련이 있는 API입니다"
  - name: "search"
    description: "검색과 관련이 있는 API입니다"
  - name: "user"
    description: "사용자와 관련이 있는 API입니다"

paths:
  /account/verify_credentials:
    $ref: "./paths/account/verify_credentials.yaml#/paths/Path"
  /coins/exchange_rate:
    $ref: "./paths/coins/exchange_rate.yaml#/paths/Path"
  /coins/shop/list:
    $ref: "./paths/coins/shop/list.yaml#/paths/Path"
  /post/show:
    get:
      description: "TODO"
      responses:
        "200":
          description: "TODO"
  /problem/class:
    $ref: "./paths/problem/class.yaml#/paths/Path"
  /problem/lookup:
    $ref: "./paths/problem/lookup.yaml#/paths/Path"
  /problem/show:
    $ref: "./paths/problem/show.yaml#/paths/Path"
  /problem/level:
    $ref: "./paths/problem/level.yaml#/paths/Path"
  /ranking/tier:
    $ref: "./paths/ranking/tier.yaml#/paths/Path"
  /ranking/class:
    $ref: "./paths/ranking/class.yaml#/paths/Path"
  /ranking/streak:
    $ref: "./paths/ranking/streak.yaml#/paths/Path"
  /ranking/contribution:
    $ref: "./paths/ranking/contribution.yaml#/paths/Path"
  /ranking/rival:
    $ref: "./paths/ranking/rival.yaml#/paths/Path"
  /ranking/reverse_rival:
    $ref: "./paths/ranking/reverse_rival.yaml#/paths/Path"
  /ranking/organization:
    $ref: "./paths/ranking/organization.yaml#/paths/Path"
  /search/suggestion:
    $ref: "./paths/search/suggestion.yaml#/paths/Path"
  /search/tag:
    $ref: "./paths/search/tag.yaml#/paths/Path"
  /search/user:
    $ref: "./paths/search/user.yaml#/paths/Path"
  /tag/list:
    get:
      description: "TODO"
      responses:
        "200":
          description: "TODO"
  /user/class_stats:
    get:
      description: "TODO"
      responses:
        "200":
          description: "TODO"
  /user/contribution_stats:
    get:
      description: "TODO"
      responses:
        "200":
          description: "TODO"
  /user/organizations:
    $ref: "./paths/user/organizations.yaml#/paths/Path"
  /user/problem_stats:
    $ref: "./paths/user/problem_stats.yaml#/paths/Path"
  /user/problem_tag_stats:
    get:
      description: "TODO"
      responses:
        "200":
          description: "TODO"
  /user/show:
    $ref: "./paths/user/show.yaml#/paths/Path"
  /user/top_100:
    $ref: "./paths/user/top_100.yaml#/paths/Path"

components:
  schemas:
    ClassDecoration:
      $ref: "./schemas/class-decoration.yaml#/components/schemas/ClassDecoration"
    CoinshopProduct:
      $ref: "./schemas/coinshop-product.yaml#/components/schemas/CoinshopProduct"
    FullUser:
      $ref: "./schemas/full-user.yaml#/components/schemas/FullUser"
    IconScheme:
      $ref: "./schemas/icon-scheme.yaml#/components/schemas/IconScheme"
    Item:
      $ref: "./schemas/item.yaml#/components/schemas/Item"
    Organization:
      $ref: "./schemas/organization.yaml#/components/schemas/Organization"
    ProblemLevel:
      $ref: "./schemas/problem-level.yaml#/components/schemas/ProblemLevel"
    RankedUser:
      $ref: "./schemas/ranked-user.yaml#/components/schemas/RankedUser"
    Settings:
      $ref: "./schemas/settings.yaml#/components/schemas/Settings"
    User:
      $ref: "./schemas/user.yaml#/components/schemas/User"
