name: Deploy

on:
  push:
    branches:
      - main

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: 'pages'
  cancel-in-progress: true

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: pnpm/action-setup@v3
        with:
          version: 8
      - uses: actions/setup-node@v4
        with:
          cache: pnpm
      - run: pnpm i
      - run: pnpm build
      - uses: stoplightio/spectral-action@v0.8.10
        with:
          file_glob: 'tsp-output/*.yaml'
  page-deployment:
    needs: [lint]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: pnpm/action-setup@v3
        with:
          version: 8
      - uses: actions/setup-node@v4
        with:
          cache: pnpm
      - run: pnpm i
      - run: pnpm build
      - name: Setup Pages
        uses: actions/configure-pages@v5
      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: build/unofficial-documentation
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
  library-deployment:
    needs: [page-deployment]
    runs-on: ubuntu-latest
    strategy:
      matrix:
        repo:
          - 'solvedac/api.ts'
          - 'solvedac/api.rs'
    steps:
      - name: Invoke Workflow
        uses: benc-uk/workflow-dispatch@v1
        with:
          workflow: Follow Up
          token: ${{ secrets.WORKFLOW_DISPATCH }}
          repo: ${{ matrix.repo }}
          inputs: |
            {
              "run-id": "${{ github.run_id }}"
            }
