name: Library Deployment

on:
  push:
    branches:
      - main

jobs:
  library-deployment:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        repo:
          - "solvedac/api.ts"
          - "solvedac/api.rs"
    steps:
      - name: Invoke Workflow
        uses: benc-uk/workflow-dispatch@v1
        with:
          workflow: Follow Up
          token: ${{ secrets.WORKFLOW_DISPATCH }}
          repo: ${{ matrix.repo }}
