name: Lint

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: stoplightio/spectral-action@v0.8.10
        with:
          file_glob: "src/*.yaml"
  library-deployment:
    needs: [lint]
    runs-on: ubuntu-latest
    if: github.event_name == 'push'
    strategy:
      matrix:
        repo:
          - "solvedac/api.ts"
          - "solvedac/api.rs"
    steps:
      - name: Invoke Workflow
        uses: benc-uk/workflow-dispatch@v1
        with:
          workflow: Follow Up
          token: ${{ secrets.WORKFLOW_DISPATCH }}
          repo: ${{ matrix.repo }}
